### PR TITLE
feat: checking for disk space before migrating

### PR DESCRIPTION
**Pull request by ricardomaraschini**
pvmigrate now checks if there is enough disk space before starting to migrate to openebs volumes.

in a nutshell:

- check what is the largest pv per node[1].
- check what is the largest non attached pv.

nodes must have, as free, double the space used of the largest pv with. total free space in a node is decreased by 15% prior to verifying if enough space is available.

this behavior can be disabled in the command line by using the flag -skip-free-space-check.

[1] the "per node" portion is determined by finding the pod where the pvc is attached and where the pod is running.

### CODE REVIEW

**Comment by laverya** [comment]
Why double the largest PV, and not the sum of the PVs?

**Comment by ricardomaraschini** [comment]
> Why double the largest PV, and not the sum of the PVs?

I thought we were migrating one PV at a time and then deleting the original. I gonna have to read the code once more. Anyway, I am closing this one and opening a new one in `kurl` repo as soon as I get it in place.

**Comment by laverya** [comment]
The logic is in the readme!

**Comment by ricardomaraschini** [comment]
> The logic is in the readme!

well, that is an option as well. shame on me.

**Pull request closed without merging**
